---
title: "SEI2HR (with Hubei, China data)"

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ECMMon)
library(deSolve)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
```


```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
modelSIR <- SEI2HRModel()
## Note that Hubei, China has nearly 59 million people. 
## Here the population is much smaller. (I that can be justified in variety of ways.)
aRealData = list( "RecoveredCases" = c(28, 28, 31, 32, 42, 45, 80, 88, 90,
      141, 168, 295, 386, 522, 633, 817, 1115, 1439, 1795, 2222, 2639,
      2686, 3459, 4774, 5623, 6639, 7862, 9128, 10337, 11788, 11881, 
     15299, 15343, 16748, 18971, 20969, 23383, 26403, 28993, 31536, 
     33934, 36208, 38557, 40592, 42033, 43500, 45235), 
   "Deaths" = c(17, 17, 24, 40, 52, 76, 125, 125, 162, 204, 249, 350, 
     414, 479, 549, 618, 699, 780, 871, 974, 1068, 1068, 1310, 1457, 
     1596, 1696, 1789, 1921, 2029, 2144, 2144, 2346, 2346, 2495, 2563,
      2615, 2641, 2682, 2727, 2761, 2803, 2835, 2871, 2902, 2931, 
     2959, 2986), 
   "Infected" = c(399, 399, 494, 689, 964, 1302, 3349, 3341, 4651, 
     5461, 6736, 10532, 12722, 15677, 18483, 20677, 23139, 24881, 
     26965, 28532, 29659, 29612, 43437, 48175, 49030, 49847, 50338, 
     50633, 49665, 48510, 48637, 46439, 46395, 45044, 43252, 41603, 
     39572, 36829, 34617, 32610, 30366, 28174, 25904, 23972, 22628, 
     21207, 19486) )
dfRealData <- 
  rbind( 
    data.frame( Time = 1:length(aRealData$RecoveredCases), Stock = "RealData RecoveredCases", Value = aRealData$RecoveredCases, stringsAsFactors = FALSE),
    data.frame( Time = 1:length(aRealData$RecoveredCases), Stock = "RealData Deaths", Value = aRealData$Deaths, stringsAsFactors = FALSE),
    data.frame( Time = 1:length(aRealData$RecoveredCases), Stock = "RealData Infected", Value = aRealData$Infected, stringsAsFactors = FALSE)
  )
```

Column {.sidebar data-width=300}
-----------------------------------------------------------------------

### Rates

```{r}
sliderInput( inputId = "contactRateISSP", label = "ISSP contact rate:", min = 0, max = 6, value = 0.56, step = 0.01 )

sliderInput( inputId = "contactRateINSP", label = "INSP contact rate:", min = 0, max = 6, value = 0.56, step = 0.01 )

sliderInput( inputId = "deathRateISSP", label = "ISSP death rate:", min = 0, max = 1, value = 0.035, step = 0.001 )

sliderInput( inputId = "deathRateINSP", label = "INSP death rate:", min = 0, max = 1, value = 0.015, step = 0.001 )

sliderInput( inputId = "sspf", label = "Severely symptomatic population fraction:", min = 0, max = 1, value = 0.2, step = 0.01 )

sliderInput( inputId = "aip", label = "Average infectious period:", min = 1, max = 90, value = 28, step = 1 )

sliderInput( inputId = "aincp", label = "Average incubation period:", min = 1, max = 90, value = 6, step = 1 )
```

### Quarantine parameters

```{r}
sliderInput( inputId = "qsd", label = "Quarantine start date:", min = 0, max = 365, value = 60, step = 1 )

sliderInput( inputId = "ql", label = "Quarantine length:", min = 0, max = 365, value = 56, step = 1 )

sliderInput( inputId = "qcrf", label = "Quarantine contact rate factor:", min = 0, max = 2, value = 0.25, step = 0.01 )
```

### Time horizon

```{r}
sliderInput( inputId = "maxTime", label = "Max time:", min = 1, max = 365, value = 365, step = 1 )
```

```{r}
sliderInput( inputId = "realDataOffset", label = "Real data offset:", min = 0, max = 300, value = 0, step = 1 )
```

### Stocks to plot

```{r}
selectInput( inputId = "stocksToPlot", 
             label = "Stocks to plot:", 
             choices = setNames( GetStocks( modelSIR, "^.*Population" ), modelSIR$Stocks[ GetStocks( modelSIR, "^.*Population" ) ]), 
             selected = setdiff( GetStocks( modelSIR, "^.*Population" ), c("TPt") ), 
             multiple = TRUE )
```

### Appearance

```{r}
checkboxInput( inputId = "moneyPlotLog10", label = "Log 10 money plots?", value = TRUE )
```


Column {data-width=650}
-----------------------------------------------------------------------

### Populations plot

```{r}
sol <- 
  reactive({
    times <- seq(0, input$maxTime, 1) 
    
    localParams <- as.list( modelSIR[["RateRules"]] )
    
    localParams[ c( "contactRateISSP", "contactRateINSP", "deathRateISSP", "deathRateINSP", "sspf") ] <- c( input$contactRateISSP, input$contactRateINSP, input$deathRateISSP / input$aip, input$deathRateINSP / input$aip, input$sspf)
    
    localParams[["contactRateINSP"]] <- function(t) { input$contactRateINSP * ifelse( input$qsd <= t && t <= input$qsd + input$ql, input$qcrf, 1 ) }
    localParams[["contactRateISSP"]] <- function(t) { input$contactRateISSP * ifelse( input$qsd <= t && t <= input$qsd + input$ql, input$qcrf, 1 ) }

    ode(y = modelSIR[["InitialConditions"]], times = times, func = modelSIR[["RHSFunction"]], parms = localParams, method = "rk4" ) 
  })
```

```{r}
dfSol <- 
  reactive({
    
    res <- as.data.frame(sol()) 
    colnames(res) <- gsub( "time", "Time", colnames(res) )
    
    res
  })
```


```{r}
renderPlot( expr = {
  
  p <-
    dfSol() %>%
    tidyr::pivot_longer( cols = colnames(dfSol())[-1], names_to = "Stock", values_to = "Value" )%>% 
    dplyr::filter( Stock %in% input$stocksToPlot ) %>%
    dplyr::mutate( Stock = paste0( Stock, ", ", modelSIR$Stocks[ Stock ] ) ) %>% 
    ggplot( ) +
    geom_line( aes( x = Time, y = Value, color = Stock), lwd = 1.2 ) +
    geom_vline( xintercept = c( input$qsd, input$qsd + input$ql), color = "gray", show.legend = TRUE ) +
    geom_point( data = dfRealData, aes( x = Time + input$realDataOffset, y = Value, color = Stock ) ) 
  
  print(p)
})
```


### Money plots

```{r}
renderPlot( expr = {
  
  p <-
    dfSol() %>%
    tidyr::pivot_longer( cols = colnames(dfSol())[-1], names_to = "Stock", values_to = "Value" )%>% 
    dplyr::filter( Stock %in% GetStocks( modelSIR, "^Money" ),  ) %>% 
    dplyr::mutate( Stock = paste0( Stock, ", ", modelSIR$Stocks[ Stock ] ))
  
  p <-
    if( input$moneyPlotLog10 ) {
      ggplot(p) +
        geom_line( aes( x = Time, y = log10(Value), color = Stock), lwd = 1.2 )
    } else {
      ggplot(p) +
        geom_line( aes( x = Time, y = Value, color = Stock), lwd = 1.2 )
    }  
  
  p <- p  + geom_vline( xintercept = c( input$qsd, input$qsd + input$ql), color = "gray", show.legend = TRUE )
  print(p)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Stock histograms

```{r}
renderPlot( expr = {
  
  p <-
    dfSol() %>%
    tidyr::pivot_longer( cols = colnames(dfSol())[-1], names_to = "Stock", values_to = "Value" )%>% 
    ggplot( ) +
    geom_histogram( aes( x = Value), bins = 30 ) +
    facet_wrap( ~Stock, scales = "free", ncol = 2 )
  
  print(p)
})
```


