---
title: "ECMMon workflows by natural commands"
author: Anton Antonov
date: "```r Sys.Date()```"
output: html_notebook
---

```{r}
library(ECMMon)
library(deSolve)
library(ggplot2)
library(magrittr)
library(ExternalParsersHookUp)
```

# Introduction

This notebooks demonstrates the construction of Epidemiologic Compartmental Modeling (ECM) workflows
using natural language commands.


# Simple commands

```{r}
ToEpidemiologyModelingWorkflowCode( "create with the model SEI2HREcon", parse = F )
```

```{r}
ToEpidemiologyModelingWorkflowCode( "simulate for 365 days", parse = F )
```

# Basic pipelines

```{r}
ToEpidemiologyModelingWorkflowCode( 
    "create with the model SEI2HR;
     simulate for 240 days;
     plot population results;
     plot solutions histograms over min time 100, max time 240;
     echo pipeline value" )
```
```{r}
obj1 <- eval(
expression(ECMMonUnit( model = SEI2HRModel()) %>%
ECMMonSimulate(maxTime = 240) %>%
ECMMonPlotSolutions( stocksSpec = ".*Population") %>%
ECMMonPlotSolutionHistograms(minTime = 100, maxTime = 240) %>%
ECMMonEchoValue())
)
```

```{r}
ecmObj2 <-
  eval( expr = ToEpidemiologyModelingWorkflowCode( 
    "create with the model SEI2HR;
     simulate for 240 days;
     plot populations results over max time 250;"
    ) ) 
```

```{r}
ecmObj2 <- 
  eval( ToEpidemiologyModelingWorkflowCode( 
  "use object ecmObj2; 
  plot solutions histograms"
) )
```

# Batch simulation

```{r}
ToEpidemiologyModelingWorkflowCode( 
    "create with the model SEI2HR;
     assign 0.7 to sspf;
     batch simulate over lpcr = 0, aincp = seq(10,40), and aip = c(20,30) for 240 days;
     plot population results" ) 
```

```{r}
ToEpidemiologyModelingWorkflowCode( 
    "create with the model SEI2HR;
     assign 0.7 to severely symptomatic population fraction;
     batch simulate over lpcr = 0, average incubation period from 10 to 40 step 5, and average infectious period = c(20,30) for 240 days;
     plot population results" ) 
```
```{r}
expand.grid(list(aincp = c(10,20,30), aip = c(20,30) ))
```


```{r}
ecmObj <- 
  eval( ToEpidemiologyModelingWorkflowCode( 
    "create with the model SEI2HR;
     assign 0.6 to sspf;
     batch simulate over lpcr = 0, aincp = c(10,20,30), aip = c(20,30) for 240 days;
     show pipeline value" ) )
```

```{r}
ggplot(ecmObj %>% ECMMonTakeValue) + 
  geom_line( aes( x = Time, y = Value, group = Stock, color = Stock ) ) +
  facet_wrap( ~lpcr + aincp + aip, ncol = 3 )
```
# Multi-site simulations

```{r}
ToEpidemiologyModelingWorkflowCode("
create object with model SEI2HR;
extend by the adjacency matrix mat1 for the migrating stocks SPt, EPt, and RPt;
simulate for 365 days;
plot population results;")
```

```{r}
mat1 <- round(matrix( runif(n = 9, min = 10, max = 100 ), nrow = 3 ))
for( i in 1:nrow(mat1) ) { mat1[i,i] <- 0 }
mat1
```

```{r}
ecmObj4 <- 
  eval(ToEpidemiologyModelingWorkflowCode("
create object with model SEI2HR;
extend by the adjacency matrix mat1 for the migrating stocks SPt, EPt, and RPt;
simulate for 365 days;
plot population results"))
```

