---
title: "Sensitivity analysis"
author: Anton Antonov
date: 2020-04-06
output: html_notebook
---

```{r}
library(ECMMon)
library(tidyverse)
library(ggplot2)
library(threejs)
```

# Introduction

In this notebook we Sensitivity Analysis using monadic pipelines.


# 2D plots

```{r}
model <- SEI2HRModel()
```

```{r}
model
```

```{r}
model[["RateRules"]] <- as.list( model[["RateRules"]] )
model[["RateRules"]][["contactRateINSP"]] <- with( list( cr = model[["RateRules"]][["contactRateINSP"]] ), function(t) { cr * ifelse( qsd <= t && t <= qsd + 56, 0.25, 1 ) } )
model[["RateRules"]][["contactRateISSP"]] <- with( list( cr = model[["RateRules"]][["contactRateISSP"]] ), function(t) { cr * ifelse( qsd <= t && t <= qsd + 56, 0.25, 1 ) } )
```

```{r}
system.time(
  dfSARes <- 
    purrr::map_df( seq(50,120,10), function( qsd ) {
      
      dfRes <- 
        ECMMonUnit( model ) %>% 
        ECMMonAssignRateValues( 
          c( 
            "contactRateINSP" =  function(t) { 0.56 * ifelse( qsd <= t && t <= qsd + 56, 0.25, 1 ) },
            "contactRateISSP" =  function(t) { 0.56 * ifelse( qsd <= t && t <= qsd + 56, 0.25, 1 ) }
          ) 
        ) %>% 
        ECMMonSimulate( 365 ) %>% 
        ECMMonGetSolutionLongForm %>% 
        ECMMonTakeValue

      cbind( QuarantineStart = qsd, dfRes %>% dplyr::filter( Stock %in% GetStocks( model, ".*Infected.*Population")) )      
    })
)
```


```{r}
summary(as.data.frame(unclass(dfSARes)))
```

```{r, fig.width=8}
ggplot(dfSARes) +
  geom_line( aes( x = Time, y = Value, color = as.factor(QuarantineStart), group = QuarantineStart ) ) +
  facet_wrap( ~Stock, scales = "free", ncol = 1 )
```

# 3D plots

```{r}
model <- SEI2HRModel()
```


```{r}
dfPairs <- expand.grid( seq(14, 12*7, 7), seq(10, 120, 5) )
dim(dfPairs)
```
```{r}
dfPairs
```

```{r}
times <- seq( 0, 365, 1)
system.time(
  dfSARes <- 
    purrr::map2_df( dfPairs$Var1, dfPairs$Var2, function( ql, qsd ) {
      
      sol <- 
        ECMMonUnit( model ) %>% 
        ECMMonAssignRateValues( 
          c( 
            "contactRateINSP" =  function(t) { 0.56 * ifelse( qsd <= t && t <= qsd + ql, 0.25, 1 ) },
            "contactRateISSP" =  function(t) { 0.56 * ifelse( qsd <= t && t <= qsd + ql, 0.25, 1 ) }
          ) 
        ) %>% 
        ECMMonSimulate( 365, method = "rk4" ) %>% 
        ECMMonTakeDeSolveSolution

      data.frame( QuarantineStart = qsd, QuarantineLength = ql, DIPt = sol[nrow(sol), "DIPt"] )      
    })
)
```

```{r}
summary(dfSARes)
```

```{r}
m <- sum( dfPairs$Var1 == min(dfPairs$Var1) )
n <- sum( dfPairs$Var2 == min(dfPairs$Var2) )
```

```{r}

```

```{r}
threejs::scatterplot3js( x = dfSARes$QuarantineStart, y = dfSARes$QuarantineLength, z = dfSARes$DIPt, size = 0.25 ) %>% 
  threejs::lines3d( 1:(m*n-n), (n+1):(m*n) )
```

